name: prodive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  # audioplayers: ^0.18.3
  auto_size_text: ^3.0.0
  buttons_tabbar: ^1.3.8
  circular_countdown_timer: ^0.2.3
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_vibrate: ^1.3.0
  google_fonts: 6.1.0
  just_audio: ^0.9.36
  provider: ^6.1.2
  sqflite: ^2.3.2
  syncfusion_flutter_charts: ^25.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/rest.mp3'
    - 'assets/timer.mp3'


